version: '3'
services:
  opensearch-node1:
    container_name: opensearch-node1
    image: opensearchproject/opensearch:2.11.1
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - opensearch-net

  opensearch-dashboards:
    container_name: opensearch-dashboards
    image: opensearchproject/opensearch-dashboards:2.11.1
    ports:
      - 5601:5601
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node1

  logstash:
    container_name: logstash
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logs:/logs
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
      OPENSEARCH_HOSTS: http://opensearch-node1:9200
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node1

volumes:
  opensearch-data:

networks:
  opensearch-net:
